[versions]

kotlin = "2.0.21"
agp = "8.5.0"
vanniktech = "0.30.0"

[libraries]


[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
vannitktech-maven-publish = {id = "com.vanniktech.maven.publish", version.ref = "vanniktech"}
